# Generated by Django 4.2 on 2025-12-17 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volleyballcourt',
            options={'ordering': ['-created_at', 'status'], 'verbose_name': 'Волейбольная площадка', 'verbose_name_plural': 'Волейбольные площадки'},
        ),
        migrations.RemoveField(
            model_name='volleyballcourt',
            name='location',
        ),
        migrations.RemoveField(
            model_name='volleyballcourt',
            name='net_height',
        ),
        migrations.AddField(
            model_name='volleyballcourt',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='volleyballcourt',
            name='has_cafe',
            field=models.BooleanField(default=False, verbose_name='Есть кафе/буфет'),
        ),
        migrations.AddField(
            model_name='volleyballcourt',
            name='has_parking',
            field=models.BooleanField(default=False, verbose_name='Есть парковка'),
        ),
        migrations.AddField(
            model_name='volleyballcourt',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='volleyballcourt',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='volleyballcourt',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='volleyballcourt',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Ссылка на фото площадки (можно загрузить на imgur.com)', verbose_name='Ссылка на фото'),
        ),
        migrations.AddField(
            model_name='volleyballcourt',
            name='price_details',
            field=models.TextField(blank=True, help_text='Например: студентам скидка 50%', verbose_name='Детали оплаты'),
        ),
        migrations.AddField(
            model_name='volleyballcourt',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Заполняется при отклонении заявки', verbose_name='Причина отклонения'),
        ),
        migrations.AddField(
            model_name='volleyballcourt',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество отзывов'),
        ),
        migrations.AddField(
            model_name='volleyballcourt',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки'),
        ),
        migrations.AddField(
            model_name='volleyballcourt',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_courts', to=settings.AUTH_USER_MODEL, verbose_name='Проверил'),
        ),
        migrations.AddField(
            model_name='volleyballcourt',
            name='website',
            field=models.URLField(blank=True, verbose_name='Сайт'),
        ),
        migrations.AddField(
            model_name='volleyballcourt',
            name='working_days',
            field=models.CharField(default='Пн-Вс', help_text='Например: Пн-Пт 8:00-22:00, Сб-Вс 9:00-20:00', max_length=100, verbose_name='Дни работы'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='address',
            field=models.CharField(max_length=300, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='court_type',
            field=models.CharField(choices=[('indoor', '🏠 Крытая'), ('outdoor', '☀️ Открытая'), ('beach', '🏖️ Пляжная')], default='outdoor', max_length=20, verbose_name='Тип площадки'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Проверена администрацией'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=1, default=18.0, max_digits=4, null=True, verbose_name='Длина (м)'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название площадки'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ На рассмотрении'), ('approved', '✅ Одобрена'), ('rejected', '❌ Отклонена'), ('needs_info', '❓ Требует уточнений')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='suggested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_courts', to=settings.AUTH_USER_MODEL, verbose_name='Предложил'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='surface',
            field=models.CharField(choices=[('wood', 'Дерево'), ('parquet', 'Паркет'), ('synthetic', 'Синтетика'), ('asphalt', 'Асфальт'), ('sand', 'Песок'), ('grass', 'Трава')], default='asphalt', max_length=20, verbose_name='Покрытие'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='tags',
            field=models.CharField(blank=True, help_text='Через запятую: волейбол, спорт, площадка, турниры', max_length=300, verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=1, default=9.0, max_digits=4, null=True, verbose_name='Ширина (м)'),
        ),
        migrations.AddIndex(
            model_name='volleyballcourt',
            index=models.Index(fields=['status', 'city'], name='myapp_volle_status_085f27_idx'),
        ),
        migrations.AddIndex(
            model_name='volleyballcourt',
            index=models.Index(fields=['is_free', 'is_lighted'], name='myapp_volle_is_free_8ea4f6_idx'),
        ),
        migrations.AddIndex(
            model_name='volleyballcourt',
            index=models.Index(fields=['rating'], name='myapp_volle_rating_3ed807_idx'),
        ),
    ]
