# Generated by Django 4.2 on 2025-12-19 18:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_alter_volleyballcourt_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='court_photos/', verbose_name='Фото')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное фото')),
            ],
            options={
                'verbose_name': 'Фото площадки',
                'verbose_name_plural': 'Фото площадок',
            },
        ),
        migrations.AlterModelOptions(
            name='volleyballcourt',
            options={'ordering': ['-suggested_at'], 'verbose_name': 'Волейбольная площадка', 'verbose_name_plural': 'Волейбольные площадки'},
        ),
        migrations.RemoveIndex(
            model_name='volleyballcourt',
            name='myapp_volle_status_085f27_idx',
        ),
        migrations.RemoveIndex(
            model_name='volleyballcourt',
            name='myapp_volle_is_free_8ea4f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='volleyballcourt',
            name='myapp_volle_rating_3ed807_idx',
        ),
        migrations.RenameField(
            model_name='volleyballcourt',
            old_name='verified_at',
            new_name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='volleyballcourt',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='volleyballcourt',
            name='has_bleachers',
        ),
        migrations.RemoveField(
            model_name='volleyballcourt',
            name='has_cafe',
        ),
        migrations.RemoveField(
            model_name='volleyballcourt',
            name='length',
        ),
        migrations.RemoveField(
            model_name='volleyballcourt',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='volleyballcourt',
            name='price_details',
        ),
        migrations.RemoveField(
            model_name='volleyballcourt',
            name='total_reviews',
        ),
        migrations.RemoveField(
            model_name='volleyballcourt',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='volleyballcourt',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='volleyballcourt',
            name='width',
        ),
        migrations.RemoveField(
            model_name='volleyballcourt',
            name='working_days',
        ),
        migrations.AddField(
            model_name='volleyballcourt',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='courts/', verbose_name='Главное фото'),
        ),
        migrations.AddField(
            model_name='volleyballcourt',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_courts', to=settings.AUTH_USER_MODEL, verbose_name='Проверил'),
        ),
        migrations.AddField(
            model_name='volleyballcourt',
            name='suggested_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата предложения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='closing_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='court_type',
            field=models.CharField(choices=[('indoor', 'Крытая'), ('outdoor', 'Открытая'), ('beach', 'Пляжная')], max_length=20, verbose_name='Тип площадки'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='has_locker_rooms',
            field=models.BooleanField(default=False, verbose_name='Раздевалки'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='has_parking',
            field=models.BooleanField(default=False, verbose_name='Парковка'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='has_showers',
            field=models.BooleanField(default=False, verbose_name='Душевые'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='is_lighted',
            field=models.BooleanField(default=False, verbose_name='Освещение'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Проверенная'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='opening_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время открытия'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена за час'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Причина отклонения'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('archived', 'В архиве')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='suggested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Предложил'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='surface',
            field=models.CharField(choices=[('wood', 'Дерево'), ('parquet', 'Паркет'), ('synthetic', 'Синтетика'), ('asphalt', 'Асфальт'), ('sand', 'Песок'), ('grass', 'Трава')], max_length=20, verbose_name='Покрытие'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='tags',
            field=models.CharField(blank=True, help_text='Через запятую: турниры, премиум, летняя и т.д.', max_length=500, verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='courtphoto',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='myapp.volleyballcourt'),
        ),
    ]
