# Generated by Django 4.2 on 2025-12-21 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_courtphoto_alter_volleyballcourt_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['game_date', 'game_time']},
        ),
        migrations.RenameField(
            model_name='game',
            old_name='date',
            new_name='game_date',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='start_time',
            new_name='game_time',
        ),
        migrations.RemoveField(
            model_name='game',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='game',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_format',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_type',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='game',
            name='location_text',
        ),
        migrations.RemoveField(
            model_name='game',
            name='min_skill_level',
        ),
        migrations.RemoveField(
            model_name='game',
            name='price_per_player',
        ),
        migrations.RemoveField(
            model_name='game',
            name='price_type',
        ),
        migrations.RemoveField(
            model_name='game',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='game',
            name='status',
        ),
        migrations.AddField(
            model_name='game',
            name='contact_name',
            field=models.CharField(blank=True, default='Не указано', max_length=100, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='game',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='game',
            name='custom_location',
            field=models.CharField(blank=True, max_length=300, verbose_name='Другое место (если нет в списке)'),
        ),
        migrations.AddField(
            model_name='game',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='game',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Приватная игра'),
        ),
        migrations.AddField(
            model_name='game',
            name='location',
            field=models.CharField(default='Не указано', max_length=300, verbose_name='Место проведения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='meeting_type',
            field=models.CharField(choices=[('training', 'Тренировка'), ('friendly', 'Товарищеская игра'), ('tournament', 'Турнир'), ('other', 'Другое')], default='friendly', max_length=50, verbose_name='Тип встречи'),
        ),
        migrations.AddField(
            model_name='game',
            name='min_players',
            field=models.PositiveIntegerField(default=4, verbose_name='Минимальное количество игроков'),
        ),
        migrations.AddField(
            model_name='game',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Организатор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Стоимость участия (руб.)'),
        ),
        migrations.AddField(
            model_name='game',
            name='skill_level',
            field=models.CharField(choices=[('any', 'Любой уровень'), ('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый'), ('pro', 'Профессиональный')], default='intermediate', max_length=50, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='game',
            name='sport_type',
            field=models.CharField(choices=[('beach', 'Пляжный волейбол (2x2)'), ('indoor', 'Зал (классика 6x6)'), ('mini', 'Мини-волейбол (4x4)'), ('mixed', 'Микст (смешанные команды)'), ('training', 'Тренировка/разминка'), ('tournament', 'Турнирная игра')], default='indoor', max_length=50, verbose_name='Тип игры'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.volleyballcourt', verbose_name='Выбранная площадка'),
        ),
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='game',
            name='max_players',
            field=models.PositiveIntegerField(default=12, verbose_name='Максимальное количество игроков'),
        ),
        migrations.AlterField(
            model_name='game',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='games_joined', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='GameParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий участника')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='myapp.game', verbose_name='Игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_participations', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Участие в игре',
                'verbose_name_plural': 'Участия в играх',
                'ordering': ['-joined_at'],
                'unique_together': {('user', 'game')},
            },
        ),
    ]
