# Generated by Django 4.2 on 2025-12-21 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0004_initial_clean'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volleyballcourt',
            options={'ordering': ['city', 'name'], 'verbose_name': 'Волейбольная площадка', 'verbose_name_plural': 'Волейбольные площадки'},
        ),
        migrations.RemoveField(
            model_name='volleyballcourt',
            name='main_photo',
        ),
        migrations.RemoveField(
            model_name='volleyballcourt',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='volleyballcourt',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='volleyballcourt',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='volleyballcourt',
            name='suggested_at',
        ),
        migrations.AddField(
            model_name='volleyballcourt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volleyballcourt',
            name='has_cafe',
            field=models.BooleanField(default=False, verbose_name='Есть кафе'),
        ),
        migrations.AddField(
            model_name='volleyballcourt',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='volleyballcourt',
            name='photo_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на фото'),
        ),
        migrations.AddField(
            model_name='volleyballcourt',
            name='price_details',
            field=models.TextField(blank=True, verbose_name='Подробнее о ценах'),
        ),
        migrations.AddField(
            model_name='volleyballcourt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='volleyballcourt',
            name='working_days',
            field=models.CharField(blank=True, default='Пн-Вс, 8:00-22:00', max_length=100, verbose_name='Дни работы'),
        ),
        migrations.AlterField(
            model_name='game',
            name='custom_location',
            field=models.CharField(blank=True, max_length=300, verbose_name='Другое место'),
        ),
        migrations.AlterField(
            model_name='game',
            name='location',
            field=models.CharField(default='Не указано', max_length=300, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='game',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='game',
            name='sport_type',
            field=models.CharField(choices=[('beach', 'Пляжный волейбол (2x2)'), ('indoor', 'Зал (классика 6x6)'), ('mini', 'Мини-волейбол (4x4)'), ('mixed', 'Микст (смешанные команды)'), ('training', 'Тренировка/разминка'), ('tournament', 'Турнирная игра')], default='indoor', max_length=50, verbose_name='Тип игры'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='closing_time',
            field=models.TimeField(default='22:00:00', verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='court_type',
            field=models.CharField(choices=[('indoor', 'Закрытый зал'), ('outdoor', 'Открытая площадка'), ('beach', 'Пляж')], default='outdoor', max_length=20, verbose_name='Тип площадки'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='has_equipment_rental',
            field=models.BooleanField(default=False, verbose_name='Прокат инвентаря'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='has_locker_rooms',
            field=models.BooleanField(default=False, verbose_name='Есть раздевалки'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='has_parking',
            field=models.BooleanField(default=False, verbose_name='Есть парковка'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='has_showers',
            field=models.BooleanField(default=False, verbose_name='Есть душ'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Бесплатно'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='is_lighted',
            field=models.BooleanField(default=False, verbose_name='Есть освещение'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Проверено'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='opening_time',
            field=models.TimeField(default='08:00:00', verbose_name='Время открытия'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена за час (руб.)'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('needs_info', 'Требует доп. информации')], default='pending', max_length=20, verbose_name='Статус модерации'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='suggested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_courts', to=settings.AUTH_USER_MODEL, verbose_name='Предложил'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='surface',
            field=models.CharField(choices=[('sand', 'Песок'), ('parquet', 'Паркет'), ('synthetic', 'Синтетика'), ('asphalt', 'Асфальт'), ('grass', 'Газон')], default='synthetic', max_length=20, verbose_name='Покрытие'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='tags',
            field=models.CharField(blank=True, max_length=200, verbose_name='Теги'),
        ),
    ]
