# Generated by Django 4.2 on 2025-12-21 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0005_alter_volleyballcourt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volleyballcourt',
            name='moderator_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий модератора'),
        ),
        migrations.AddField(
            model_name='volleyballcourt',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки'),
        ),
        migrations.AddField(
            model_name='volleyballcourt',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_courts', to=settings.AUTH_USER_MODEL, verbose_name='Проверил'),
        ),
    ]
