# Generated by Django 4.2 on 2025-12-21 13:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0006_volleyballcourt_moderator_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Номер брони')),
                ('booking_date', models.DateField(verbose_name='Дата бронирования')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('hours', models.PositiveIntegerField(default=1, verbose_name='Количество часов')),
                ('participants_count', models.PositiveIntegerField(default=6, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(24)], verbose_name='Количество участников')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за час')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Сумма депозита')),
                ('status', models.CharField(choices=[('pending', '⏳ Ожидает подтверждения'), ('confirmed', '✅ Подтверждено'), ('cancelled', '❌ Отменено'), ('completed', '🏐 Завершено'), ('rejected', '🚫 Отклонено')], default='pending', max_length=20, verbose_name='Статус бронирования')),
                ('payment_status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('partial', 'Частично оплачено'), ('refunded', 'Возвращено'), ('cancelled', 'Отмена оплаты')], default='pending', max_length=20, verbose_name='Статус оплаты')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Контактное лицо')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Контактный телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email для связи')),
                ('special_requests', models.TextField(blank=True, verbose_name='Особые пожелания')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'Бронирование площадки',
                'verbose_name_plural': 'Бронирования площадок',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking_confirmed', 'Бронирование подтверждено'), ('booking_cancelled', 'Бронирование отменено'), ('booking_reminder', 'Напоминание о игре'), ('payment_success', 'Оплата прошла успешно'), ('payment_failed', 'Ошибка оплаты'), ('new_message', 'Новое сообщение'), ('friend_request', 'Запрос в друзья'), ('game_invite', 'Приглашение на игру'), ('system', 'Системное уведомление')], max_length=30, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('related_object_type', models.CharField(blank=True, max_length=50, verbose_name='Тип объекта')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=50, unique=True, verbose_name='Номер платежа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('payment_method', models.CharField(choices=[('card', 'Банковская карта'), ('sbp', 'СБП (СБП)'), ('cash', 'Наличные'), ('transfer', 'Банковский перевод'), ('other', 'Другое')], max_length=20, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('processing', 'В обработке'), ('completed', 'Завершено'), ('failed', 'Не удалось'), ('refunded', 'Возвращено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус платежа')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID транзакции')),
                ('bank_response', models.TextField(blank=True, verbose_name='Ответ банка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='myapp.courtbooking', verbose_name='Бронирование')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_overall', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Общая оценка')),
                ('rating_condition', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Состояние площадки')),
                ('rating_service', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Качество обслуживания')),
                ('rating_price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Соотношение цена/качество')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок отзыва')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('pros', models.TextField(blank=True, verbose_name='Достоинства')),
                ('cons', models.TextField(blank=True, verbose_name='Недостатки')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Проверенный отзыв')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='myapp.courtbooking', verbose_name='Бронирование')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Забронирован')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена слота')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_slots', to='myapp.courtbooking', verbose_name='Бронирование')),
            ],
            options={
                'verbose_name': 'Временной слот',
                'verbose_name_plural': 'Временные слоты',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='friendship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_bookings',
            field=models.BooleanField(default=True, verbose_name='Уведомлять о бронированиях'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_messages',
            field=models.BooleanField(default=True, verbose_name='Уведомлять о сообщениях'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_news',
            field=models.BooleanField(default=False, verbose_name='Уведомлять о новостях'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='volleyballcourt',
            name='advance_booking_days',
            field=models.PositiveIntegerField(default=14, verbose_name='Макс. дней для бронирования вперед'),
        ),
        migrations.AddField(
            model_name='volleyballcourt',
            name='booking_enabled',
            field=models.BooleanField(default=True, verbose_name='Бронирование доступно'),
        ),
        migrations.AddField(
            model_name='volleyballcourt',
            name='max_booking_hours',
            field=models.PositiveIntegerField(default=3, verbose_name='Максимальное время брони (часы)'),
        ),
        migrations.AddField(
            model_name='volleyballcourt',
            name='min_booking_hours',
            field=models.PositiveIntegerField(default=1, verbose_name='Минимальное время брони (часы)'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('accepted', 'Принято'), ('rejected', 'Отклонено'), ('blocked', 'Заблокировано')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='gameparticipation',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, default='Москва', max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='play_days',
            field=models.CharField(blank=True, default='вечера будних, выходные', max_length=100, verbose_name='Дни для игр'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='play_style',
            field=models.CharField(blank=True, max_length=50, verbose_name='Стиль игры'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, choices=[('setter', 'Связующий'), ('outside', 'Доигровщик'), ('opposite', 'Диагональный'), ('middle', 'Центральный блокирующий'), ('libero', 'Либеро'), ('all', 'Универсал')], max_length=20, verbose_name='Основная позиция'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='positions',
            field=models.CharField(blank=True, help_text='Укажите через запятую', max_length=100, verbose_name='Все позиции'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='city',
            field=models.CharField(default='Москва', max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ На модерации'), ('approved', '✅ Одобрено'), ('rejected', '❌ Отклонено'), ('needs_info', '❓ Требует уточнений')], default='pending', max_length=20, verbose_name='Статус модерации'),
        ),
        migrations.AlterField(
            model_name='volleyballcourt',
            name='working_days',
            field=models.CharField(blank=True, default='Пн-Вс', max_length=100, verbose_name='Дни работы'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='myapp.volleyballcourt', verbose_name='Площадка'),
        ),
        migrations.AddField(
            model_name='review',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='myapp.volleyballcourt', verbose_name='Площадка'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='courtbooking',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='myapp.volleyballcourt', verbose_name='Площадка'),
        ),
        migrations.AddField(
            model_name='courtbooking',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='booked_games', to=settings.AUTH_USER_MODEL, verbose_name='Участники игры'),
        ),
        migrations.AddField(
            model_name='courtbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('court', 'date', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('court', 'user')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='myapp_notif_user_id_da55a8_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='myapp_notif_created_92a5b3_idx'),
        ),
        migrations.AddIndex(
            model_name='courtbooking',
            index=models.Index(fields=['booking_date', 'start_time'], name='myapp_court_booking_c4a969_idx'),
        ),
        migrations.AddIndex(
            model_name='courtbooking',
            index=models.Index(fields=['status'], name='myapp_court_status_2ba837_idx'),
        ),
        migrations.AddIndex(
            model_name='courtbooking',
            index=models.Index(fields=['user'], name='myapp_court_user_id_d5e030_idx'),
        ),
    ]
