# Generated by Django 6.0.1 on 2026-01-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_courtbooking_notification_payment_review_timeslot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('court_type', models.CharField(choices=[('indoor', 'Закрытый зал'), ('outdoor', 'Открытая площадка'), ('beach', 'Пляжная площадка')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
