# Generated by Django 6.0.1 on 2026-01-20 19:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_court'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Район проживания'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorited_by', to='myapp.volleyballcourt', verbose_name='Любимая площадка'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(100)], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='О себе'),
        ),
    ]
